//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DFARMR_IVR1.GET_DIV_PAYEE_DETAILS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Z_WS_GET_DIV_PAYEE_DETAILSBinding", Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_WS_GET_DIV_PAYEE_DETAILSService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Z_WS_GET_DIV_PAYEE_DETAILSOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Z_WS_GET_DIV_PAYEE_DETAILSService() {
            this.Url = global::DFARMR_IVR1.Properties.Settings.Default.DFARMR_IVR1_DOES_PASSWORD_EXIST_Z_WS_DOES_PASSWORD_EXIST_MSAService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Z_WS_GET_DIV_PAYEE_DETAILSCompletedEventHandler Z_WS_GET_DIV_PAYEE_DETAILSCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sap.com/Z_WS_GET_DIV_PAYEE_DETAILS", RequestNamespace="urn:sap-com:document:sap:rfc:functions", ResponseElementName="Z_WS_GET_DIV_PAYEE_DETAILS.Response", ResponseNamespace="urn:sap-com:document:sap:rfc:functions", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("E_DIV_PAYEE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZDIV_PAYEE_DETAILS[] Z_WS_GET_DIV_PAYEE_DETAILS([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string I_LOGINID, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string I_MSA, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string I_PAYEE, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string E_STATUS) {
            object[] results = this.Invoke("Z_WS_GET_DIV_PAYEE_DETAILS", new object[] {
                        I_LOGINID,
                        I_MSA,
                        I_PAYEE});
            E_STATUS = ((string)(results[1]));
            return ((ZDIV_PAYEE_DETAILS[])(results[0]));
        }
        
        /// <remarks/>
        public void Z_WS_GET_DIV_PAYEE_DETAILSAsync(string I_LOGINID, string I_MSA, string I_PAYEE) {
            this.Z_WS_GET_DIV_PAYEE_DETAILSAsync(I_LOGINID, I_MSA, I_PAYEE, null);
        }
        
        /// <remarks/>
        public void Z_WS_GET_DIV_PAYEE_DETAILSAsync(string I_LOGINID, string I_MSA, string I_PAYEE, object userState) {
            if ((this.Z_WS_GET_DIV_PAYEE_DETAILSOperationCompleted == null)) {
                this.Z_WS_GET_DIV_PAYEE_DETAILSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZ_WS_GET_DIV_PAYEE_DETAILSOperationCompleted);
            }
            this.InvokeAsync("Z_WS_GET_DIV_PAYEE_DETAILS", new object[] {
                        I_LOGINID,
                        I_MSA,
                        I_PAYEE}, this.Z_WS_GET_DIV_PAYEE_DETAILSOperationCompleted, userState);
        }
        
        private void OnZ_WS_GET_DIV_PAYEE_DETAILSOperationCompleted(object arg) {
            if ((this.Z_WS_GET_DIV_PAYEE_DETAILSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Z_WS_GET_DIV_PAYEE_DETAILSCompleted(this, new Z_WS_GET_DIV_PAYEE_DETAILSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZDIV_PAYEE_DETAILS {
        
        private string dIVISIONField;
        
        private string dIV_NAMEField;
        
        private string pAYEEField;
        
        private string pAYEE_NAMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DIVISION {
            get {
                return this.dIVISIONField;
            }
            set {
                this.dIVISIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DIV_NAME {
            get {
                return this.dIV_NAMEField;
            }
            set {
                this.dIV_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PAYEE {
            get {
                return this.pAYEEField;
            }
            set {
                this.pAYEEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PAYEE_NAME {
            get {
                return this.pAYEE_NAMEField;
            }
            set {
                this.pAYEE_NAMEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void Z_WS_GET_DIV_PAYEE_DETAILSCompletedEventHandler(object sender, Z_WS_GET_DIV_PAYEE_DETAILSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Z_WS_GET_DIV_PAYEE_DETAILSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Z_WS_GET_DIV_PAYEE_DETAILSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZDIV_PAYEE_DETAILS[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZDIV_PAYEE_DETAILS[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string E_STATUS {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591