//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFARMR_IVR1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        public string DFARMR_IVR1_NewGetTestResults_WebReference_Z_WS_GET_TEST_RESULTSService {
            get {
                return ((string)(this["DFARMR_IVR1_NewGetTestResults_WebReference_Z_WS_GET_TEST_RESULTSService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        public string DFARMR_IVR1_GET_DIV_PAYEE_DETAILS_Z_WS_GET_DIV_PAYEE_DETAILSService {
            get {
                return ((string)(this["DFARMR_IVR1_GET_DIV_PAYEE_DETAILS_Z_WS_GET_DIV_PAYEE_DETAILSService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        public string DFARMR_IVR1_DOES_PASSWORD_EXIST_Z_WS_DOES_PASSWORD_EXIST_MSAService {
            get {
                return ((string)(this["DFARMR_IVR1_DOES_PASSWORD_EXIST_Z_WS_DOES_PASSWORD_EXIST_MSAService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        public string DFARMR_IVR1_GET_QUERY_VIEW_DATA_RRW3_GET_QUERY_VIEW_DATAService {
            get {
                return ((string)(this["DFARMR_IVR1_GET_QUERY_VIEW_DATA_RRW3_GET_QUERY_VIEW_DATAService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        public string DFARMR_IVR1_NewDoesDivisionExist_WebReference_Z_WS_DOES_DIVISION_EXISTService {
            get {
                return ((string)(this["DFARMR_IVR1_NewDoesDivisionExist_WebReference_Z_WS_DOES_DIVISION_EXISTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        public string DFARMR_IVR1_NewDoesPasswordExist_WebReference_Z_WS_DOES_PASSWORD_EXISTService {
            get {
                return ((string)(this["DFARMR_IVR1_NewDoesPasswordExist_WebReference_Z_WS_DOES_PASSWORD_EXISTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        public string DFARMR_IVR1_NewDoesProducerExist_WebReference_Z_WS_DOES_PRODUCER_EXISTService {
            get {
                return ((string)(this["DFARMR_IVR1_NewDoesProducerExist_WebReference_Z_WS_DOES_PRODUCER_EXISTService"]));
            }
        }
    }
}
