//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DFARMR_IVR1.NewGetTestResults.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Z_WS_GET_TEST_RESULTSBinding", Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_WS_GET_TEST_RESULTSService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Z_WS_GET_TEST_RESULTSOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Z_WS_GET_TEST_RESULTSService() {
            this.Url = global::DFARMR_IVR1.Properties.Settings.Default.DFARMR_IVR1_DOES_PASSWORD_EXIST_Z_WS_DOES_PASSWORD_EXIST_MSAService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Z_WS_GET_TEST_RESULTSCompletedEventHandler Z_WS_GET_TEST_RESULTSCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sap.com/Z_WS_GET_TEST_RESULTS", RequestNamespace="urn:sap-com:document:sap:rfc:functions", ResponseElementName="Z_WS_GET_TEST_RESULTS.Response", ResponseNamespace="urn:sap-com:document:sap:rfc:functions", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("E_STATUS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Z_WS_GET_TEST_RESULTS([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string I_DIVISION, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string I_ENDDT, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string I_PRODUCER, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string I_REPORTID, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string I_STARTDT, [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] out ZMVRU_OUTPUT_NET[] E_TESTRESULTS) {
            object[] results = this.Invoke("Z_WS_GET_TEST_RESULTS", new object[] {
                        I_DIVISION,
                        I_ENDDT,
                        I_PRODUCER,
                        I_REPORTID,
                        I_STARTDT});
            E_TESTRESULTS = ((ZMVRU_OUTPUT_NET[])(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Z_WS_GET_TEST_RESULTSAsync(string I_DIVISION, string I_ENDDT, string I_PRODUCER, string I_REPORTID, string I_STARTDT) {
            this.Z_WS_GET_TEST_RESULTSAsync(I_DIVISION, I_ENDDT, I_PRODUCER, I_REPORTID, I_STARTDT, null);
        }
        
        /// <remarks/>
        public void Z_WS_GET_TEST_RESULTSAsync(string I_DIVISION, string I_ENDDT, string I_PRODUCER, string I_REPORTID, string I_STARTDT, object userState) {
            if ((this.Z_WS_GET_TEST_RESULTSOperationCompleted == null)) {
                this.Z_WS_GET_TEST_RESULTSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZ_WS_GET_TEST_RESULTSOperationCompleted);
            }
            this.InvokeAsync("Z_WS_GET_TEST_RESULTS", new object[] {
                        I_DIVISION,
                        I_ENDDT,
                        I_PRODUCER,
                        I_REPORTID,
                        I_STARTDT}, this.Z_WS_GET_TEST_RESULTSOperationCompleted, userState);
        }
        
        private void OnZ_WS_GET_TEST_RESULTSOperationCompleted(object arg) {
            if ((this.Z_WS_GET_TEST_RESULTSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Z_WS_GET_TEST_RESULTSCompleted(this, new Z_WS_GET_TEST_RESULTSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMVRU_OUTPUT_NET {
        
        private ZMVRU_FIELD_LINE_NET[] pICKUPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZMVRU_FIELD_LINE_NET[] PICKUP {
            get {
                return this.pICKUPField;
            }
            set {
                this.pICKUPField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMVRU_FIELD_LINE_NET {
        
        private ZMVRU_FIELD_TAB_NET fIELDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZMVRU_FIELD_TAB_NET FIELD {
            get {
                return this.fIELDField;
            }
            set {
                this.fIELDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMVRU_FIELD_TAB_NET {
        
        private string cATEGORYField;
        
        private string nAMEField;
        
        private string vALUEField;
        
        private string tESTDESCField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CATEGORY {
            get {
                return this.cATEGORYField;
            }
            set {
                this.cATEGORYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VALUE {
            get {
                return this.vALUEField;
            }
            set {
                this.vALUEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TESTDESC {
            get {
                return this.tESTDESCField;
            }
            set {
                this.tESTDESCField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void Z_WS_GET_TEST_RESULTSCompletedEventHandler(object sender, Z_WS_GET_TEST_RESULTSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Z_WS_GET_TEST_RESULTSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Z_WS_GET_TEST_RESULTSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public ZMVRU_OUTPUT_NET[] E_TESTRESULTS {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZMVRU_OUTPUT_NET[])(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591