//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFARMR_IVR1.GetQueryViewData {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="GetQueryViewData.RRW3_GET_QUERY_VIEW_DATAPortType")]
    public interface RRW3_GET_QUERY_VIEW_DATAPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sap.com/RRW3_GET_QUERY_VIEW_DATA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DFARMR_IVR1.GetQueryViewData.RRW3_GET_QUERY_VIEW_DATAResponse RRW3_GET_QUERY_VIEW_DATA(DFARMR_IVR1.GetQueryViewData.RRW3_GET_QUERY_VIEW_DATARequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sap.com/RRW3_GET_QUERY_VIEW_DATA", ReplyAction="*")]
        System.Threading.Tasks.Task<DFARMR_IVR1.GetQueryViewData.RRW3_GET_QUERY_VIEW_DATAResponse> RRW3_GET_QUERY_VIEW_DATAAsync(DFARMR_IVR1.GetQueryViewData.RRW3_GET_QUERY_VIEW_DATARequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class W3QUERY : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nAMEField;
        
        private string vALUEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
                this.RaisePropertyChanged("NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string VALUE {
            get {
                return this.vALUEField;
            }
            set {
                this.vALUEField = value;
                this.RaisePropertyChanged("VALUE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class RRWS_S_TEXT_SYMBOLS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sYM_TYPEField;
        
        private string sYM_TIMEDEPField;
        
        private string sYM_NAMEField;
        
        private string sYM_FSField;
        
        private string sYM_BEGIN_GROUPField;
        
        private string sYM_CAPTIONField;
        
        private string sYM_VALUE_TYPEField;
        
        private string sYM_VALUEField;
        
        private string sYM_OUTPUTLENField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string SYM_TYPE {
            get {
                return this.sYM_TYPEField;
            }
            set {
                this.sYM_TYPEField = value;
                this.RaisePropertyChanged("SYM_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string SYM_TIMEDEP {
            get {
                return this.sYM_TIMEDEPField;
            }
            set {
                this.sYM_TIMEDEPField = value;
                this.RaisePropertyChanged("SYM_TIMEDEP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string SYM_NAME {
            get {
                return this.sYM_NAMEField;
            }
            set {
                this.sYM_NAMEField = value;
                this.RaisePropertyChanged("SYM_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string SYM_FS {
            get {
                return this.sYM_FSField;
            }
            set {
                this.sYM_FSField = value;
                this.RaisePropertyChanged("SYM_FS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string SYM_BEGIN_GROUP {
            get {
                return this.sYM_BEGIN_GROUPField;
            }
            set {
                this.sYM_BEGIN_GROUPField = value;
                this.RaisePropertyChanged("SYM_BEGIN_GROUP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string SYM_CAPTION {
            get {
                return this.sYM_CAPTIONField;
            }
            set {
                this.sYM_CAPTIONField = value;
                this.RaisePropertyChanged("SYM_CAPTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string SYM_VALUE_TYPE {
            get {
                return this.sYM_VALUE_TYPEField;
            }
            set {
                this.sYM_VALUE_TYPEField = value;
                this.RaisePropertyChanged("SYM_VALUE_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string SYM_VALUE {
            get {
                return this.sYM_VALUEField;
            }
            set {
                this.sYM_VALUEField = value;
                this.RaisePropertyChanged("SYM_VALUE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string SYM_OUTPUTLEN {
            get {
                return this.sYM_OUTPUTLENField;
            }
            set {
                this.sYM_OUTPUTLENField = value;
                this.RaisePropertyChanged("SYM_OUTPUTLEN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class RRWS_S_CELL : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cELL_ORDINALField;
        
        private string vALUEField;
        
        private string fORMATTED_VALUEField;
        
        private string vALUE_TYPEField;
        
        private string cURRENCYField;
        
        private string uNITField;
        
        private string mWKZField;
        
        private string nUM_SCALEField;
        
        private string nUM_PRECField;
        
        private string cELL_STATUSField;
        
        private string bACK_COLORField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CELL_ORDINAL {
            get {
                return this.cELL_ORDINALField;
            }
            set {
                this.cELL_ORDINALField = value;
                this.RaisePropertyChanged("CELL_ORDINAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string VALUE {
            get {
                return this.vALUEField;
            }
            set {
                this.vALUEField = value;
                this.RaisePropertyChanged("VALUE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string FORMATTED_VALUE {
            get {
                return this.fORMATTED_VALUEField;
            }
            set {
                this.fORMATTED_VALUEField = value;
                this.RaisePropertyChanged("FORMATTED_VALUE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string VALUE_TYPE {
            get {
                return this.vALUE_TYPEField;
            }
            set {
                this.vALUE_TYPEField = value;
                this.RaisePropertyChanged("VALUE_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string CURRENCY {
            get {
                return this.cURRENCYField;
            }
            set {
                this.cURRENCYField = value;
                this.RaisePropertyChanged("CURRENCY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string UNIT {
            get {
                return this.uNITField;
            }
            set {
                this.uNITField = value;
                this.RaisePropertyChanged("UNIT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MWKZ {
            get {
                return this.mWKZField;
            }
            set {
                this.mWKZField = value;
                this.RaisePropertyChanged("MWKZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string NUM_SCALE {
            get {
                return this.nUM_SCALEField;
            }
            set {
                this.nUM_SCALEField = value;
                this.RaisePropertyChanged("NUM_SCALE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string NUM_PREC {
            get {
                return this.nUM_PRECField;
            }
            set {
                this.nUM_PRECField = value;
                this.RaisePropertyChanged("NUM_PREC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string CELL_STATUS {
            get {
                return this.cELL_STATUSField;
            }
            set {
                this.cELL_STATUSField = value;
                this.RaisePropertyChanged("CELL_STATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string BACK_COLOR {
            get {
                return this.bACK_COLORField;
            }
            set {
                this.bACK_COLORField = value;
                this.RaisePropertyChanged("BACK_COLOR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class RRWS_S_ATTRINM : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aTTRINMField;
        
        private string cAPTIONField;
        
        private string cHAPRSNTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ATTRINM {
            get {
                return this.aTTRINMField;
            }
            set {
                this.aTTRINMField = value;
                this.RaisePropertyChanged("ATTRINM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CAPTION {
            get {
                return this.cAPTIONField;
            }
            set {
                this.cAPTIONField = value;
                this.RaisePropertyChanged("CAPTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CHAPRSNT {
            get {
                return this.cHAPRSNTField;
            }
            set {
                this.cHAPRSNTField = value;
                this.RaisePropertyChanged("CHAPRSNT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class RRWS_SX_AXIS_CHARS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cHANMField;
        
        private string hIENMField;
        
        private string vERSIONField;
        
        private string dATETOField;
        
        private string cAPTIONField;
        
        private string cHAPRSNTField;
        
        private string cHATYPField;
        
        private RRWS_S_ATTRINM[] aTTRINMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CHANM {
            get {
                return this.cHANMField;
            }
            set {
                this.cHANMField = value;
                this.RaisePropertyChanged("CHANM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string HIENM {
            get {
                return this.hIENMField;
            }
            set {
                this.hIENMField = value;
                this.RaisePropertyChanged("HIENM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string VERSION {
            get {
                return this.vERSIONField;
            }
            set {
                this.vERSIONField = value;
                this.RaisePropertyChanged("VERSION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string DATETO {
            get {
                return this.dATETOField;
            }
            set {
                this.dATETOField = value;
                this.RaisePropertyChanged("DATETO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string CAPTION {
            get {
                return this.cAPTIONField;
            }
            set {
                this.cAPTIONField = value;
                this.RaisePropertyChanged("CAPTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string CHAPRSNT {
            get {
                return this.cHAPRSNTField;
            }
            set {
                this.cHAPRSNTField = value;
                this.RaisePropertyChanged("CHAPRSNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string CHATYP {
            get {
                return this.cHATYPField;
            }
            set {
                this.cHATYPField = value;
                this.RaisePropertyChanged("CHATYP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public RRWS_S_ATTRINM[] ATTRINM {
            get {
                return this.aTTRINMField;
            }
            set {
                this.aTTRINMField = value;
                this.RaisePropertyChanged("ATTRINM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class RRWS_SX_AXIS_INFO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aXISField;
        
        private int nCHARSField;
        
        private bool nCHARSFieldSpecified;
        
        private int nCOORDSField;
        
        private bool nCOORDSFieldSpecified;
        
        private RRWS_SX_AXIS_CHARS[] cHARSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string AXIS {
            get {
                return this.aXISField;
            }
            set {
                this.aXISField = value;
                this.RaisePropertyChanged("AXIS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int NCHARS {
            get {
                return this.nCHARSField;
            }
            set {
                this.nCHARSField = value;
                this.RaisePropertyChanged("NCHARS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NCHARSSpecified {
            get {
                return this.nCHARSFieldSpecified;
            }
            set {
                this.nCHARSFieldSpecified = value;
                this.RaisePropertyChanged("NCHARSSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int NCOORDS {
            get {
                return this.nCOORDSField;
            }
            set {
                this.nCOORDSField = value;
                this.RaisePropertyChanged("NCOORDS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NCOORDSSpecified {
            get {
                return this.nCOORDSFieldSpecified;
            }
            set {
                this.nCOORDSFieldSpecified = value;
                this.RaisePropertyChanged("NCOORDSSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public RRWS_SX_AXIS_CHARS[] CHARS {
            get {
                return this.cHARSField;
            }
            set {
                this.cHARSField = value;
                this.RaisePropertyChanged("CHARS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class RRWS_S_ATTRIBUTES : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aTTRINMField;
        
        private string cAPTIONField;
        
        private string aTTRIVLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ATTRINM {
            get {
                return this.aTTRINMField;
            }
            set {
                this.aTTRINMField = value;
                this.RaisePropertyChanged("ATTRINM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CAPTION {
            get {
                return this.cAPTIONField;
            }
            set {
                this.cAPTIONField = value;
                this.RaisePropertyChanged("CAPTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ATTRIVL {
            get {
                return this.aTTRIVLField;
            }
            set {
                this.aTTRIVLField = value;
                this.RaisePropertyChanged("ATTRIVL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class RRWS_SX_TUPLE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tUPLE_ORDINALField;
        
        private string cHANMField;
        
        private string cAPTIONField;
        
        private string cHAVLField;
        
        private string cHAVL_EXTField;
        
        private string nIOBJNMField;
        
        private string tLEVELField;
        
        private string dRILLSTATEField;
        
        private string oPTField;
        
        private string sIGNField;
        
        private RRWS_S_ATTRIBUTES[] aTTRIBUTESField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TUPLE_ORDINAL {
            get {
                return this.tUPLE_ORDINALField;
            }
            set {
                this.tUPLE_ORDINALField = value;
                this.RaisePropertyChanged("TUPLE_ORDINAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CHANM {
            get {
                return this.cHANMField;
            }
            set {
                this.cHANMField = value;
                this.RaisePropertyChanged("CHANM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CAPTION {
            get {
                return this.cAPTIONField;
            }
            set {
                this.cAPTIONField = value;
                this.RaisePropertyChanged("CAPTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CHAVL {
            get {
                return this.cHAVLField;
            }
            set {
                this.cHAVLField = value;
                this.RaisePropertyChanged("CHAVL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string CHAVL_EXT {
            get {
                return this.cHAVL_EXTField;
            }
            set {
                this.cHAVL_EXTField = value;
                this.RaisePropertyChanged("CHAVL_EXT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string NIOBJNM {
            get {
                return this.nIOBJNMField;
            }
            set {
                this.nIOBJNMField = value;
                this.RaisePropertyChanged("NIOBJNM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string TLEVEL {
            get {
                return this.tLEVELField;
            }
            set {
                this.tLEVELField = value;
                this.RaisePropertyChanged("TLEVEL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string DRILLSTATE {
            get {
                return this.dRILLSTATEField;
            }
            set {
                this.dRILLSTATEField = value;
                this.RaisePropertyChanged("DRILLSTATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string OPT {
            get {
                return this.oPTField;
            }
            set {
                this.oPTField = value;
                this.RaisePropertyChanged("OPT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string SIGN {
            get {
                return this.sIGNField;
            }
            set {
                this.sIGNField = value;
                this.RaisePropertyChanged("SIGN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public RRWS_S_ATTRIBUTES[] ATTRIBUTES {
            get {
                return this.aTTRIBUTESField;
            }
            set {
                this.aTTRIBUTESField = value;
                this.RaisePropertyChanged("ATTRIBUTES");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class RRWS_SX_AXIS_DATA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aXISField;
        
        private RRWS_SX_TUPLE[] sETField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string AXIS {
            get {
                return this.aXISField;
            }
            set {
                this.aXISField = value;
                this.RaisePropertyChanged("AXIS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public RRWS_SX_TUPLE[] SET {
            get {
                return this.sETField;
            }
            set {
                this.sETField = value;
                this.RaisePropertyChanged("SET");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RRW3_GET_QUERY_VIEW_DATA", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class RRW3_GET_QUERY_VIEW_DATARequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string I_INFOPROVIDER;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string I_QUERY;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=2)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DFARMR_IVR1.GetQueryViewData.W3QUERY[] I_T_PARAMETER;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string I_VIEW_ID;
        
        public RRW3_GET_QUERY_VIEW_DATARequest() {
        }
        
        public RRW3_GET_QUERY_VIEW_DATARequest(string I_INFOPROVIDER, string I_QUERY, DFARMR_IVR1.GetQueryViewData.W3QUERY[] I_T_PARAMETER, string I_VIEW_ID) {
            this.I_INFOPROVIDER = I_INFOPROVIDER;
            this.I_QUERY = I_QUERY;
            this.I_T_PARAMETER = I_T_PARAMETER;
            this.I_VIEW_ID = I_VIEW_ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RRW3_GET_QUERY_VIEW_DATA.Response", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class RRW3_GET_QUERY_VIEW_DATAResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DFARMR_IVR1.GetQueryViewData.RRWS_SX_AXIS_DATA[] E_AXIS_DATA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DFARMR_IVR1.GetQueryViewData.RRWS_SX_AXIS_INFO[] E_AXIS_INFO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=2)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DFARMR_IVR1.GetQueryViewData.RRWS_S_CELL[] E_CELL_DATA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=3)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DFARMR_IVR1.GetQueryViewData.RRWS_S_TEXT_SYMBOLS[] E_TXT_SYMBOLS;
        
        public RRW3_GET_QUERY_VIEW_DATAResponse() {
        }
        
        public RRW3_GET_QUERY_VIEW_DATAResponse(DFARMR_IVR1.GetQueryViewData.RRWS_SX_AXIS_DATA[] E_AXIS_DATA, DFARMR_IVR1.GetQueryViewData.RRWS_SX_AXIS_INFO[] E_AXIS_INFO, DFARMR_IVR1.GetQueryViewData.RRWS_S_CELL[] E_CELL_DATA, DFARMR_IVR1.GetQueryViewData.RRWS_S_TEXT_SYMBOLS[] E_TXT_SYMBOLS) {
            this.E_AXIS_DATA = E_AXIS_DATA;
            this.E_AXIS_INFO = E_AXIS_INFO;
            this.E_CELL_DATA = E_CELL_DATA;
            this.E_TXT_SYMBOLS = E_TXT_SYMBOLS;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RRW3_GET_QUERY_VIEW_DATAPortTypeChannel : DFARMR_IVR1.GetQueryViewData.RRW3_GET_QUERY_VIEW_DATAPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RRW3_GET_QUERY_VIEW_DATAPortTypeClient : System.ServiceModel.ClientBase<DFARMR_IVR1.GetQueryViewData.RRW3_GET_QUERY_VIEW_DATAPortType>, DFARMR_IVR1.GetQueryViewData.RRW3_GET_QUERY_VIEW_DATAPortType {
        
        public RRW3_GET_QUERY_VIEW_DATAPortTypeClient() {
        }
        
        public RRW3_GET_QUERY_VIEW_DATAPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RRW3_GET_QUERY_VIEW_DATAPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RRW3_GET_QUERY_VIEW_DATAPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RRW3_GET_QUERY_VIEW_DATAPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DFARMR_IVR1.GetQueryViewData.RRW3_GET_QUERY_VIEW_DATAResponse DFARMR_IVR1.GetQueryViewData.RRW3_GET_QUERY_VIEW_DATAPortType.RRW3_GET_QUERY_VIEW_DATA(DFARMR_IVR1.GetQueryViewData.RRW3_GET_QUERY_VIEW_DATARequest request) {
            return base.Channel.RRW3_GET_QUERY_VIEW_DATA(request);
        }
        
        public DFARMR_IVR1.GetQueryViewData.RRWS_SX_AXIS_DATA[] RRW3_GET_QUERY_VIEW_DATA(string I_INFOPROVIDER, string I_QUERY, DFARMR_IVR1.GetQueryViewData.W3QUERY[] I_T_PARAMETER, string I_VIEW_ID, out DFARMR_IVR1.GetQueryViewData.RRWS_SX_AXIS_INFO[] E_AXIS_INFO, out DFARMR_IVR1.GetQueryViewData.RRWS_S_CELL[] E_CELL_DATA, out DFARMR_IVR1.GetQueryViewData.RRWS_S_TEXT_SYMBOLS[] E_TXT_SYMBOLS) {
            DFARMR_IVR1.GetQueryViewData.RRW3_GET_QUERY_VIEW_DATARequest inValue = new DFARMR_IVR1.GetQueryViewData.RRW3_GET_QUERY_VIEW_DATARequest();
            inValue.I_INFOPROVIDER = I_INFOPROVIDER;
            inValue.I_QUERY = I_QUERY;
            inValue.I_T_PARAMETER = I_T_PARAMETER;
            inValue.I_VIEW_ID = I_VIEW_ID;
            DFARMR_IVR1.GetQueryViewData.RRW3_GET_QUERY_VIEW_DATAResponse retVal = ((DFARMR_IVR1.GetQueryViewData.RRW3_GET_QUERY_VIEW_DATAPortType)(this)).RRW3_GET_QUERY_VIEW_DATA(inValue);
            E_AXIS_INFO = retVal.E_AXIS_INFO;
            E_CELL_DATA = retVal.E_CELL_DATA;
            E_TXT_SYMBOLS = retVal.E_TXT_SYMBOLS;
            return retVal.E_AXIS_DATA;
        }
        
        public System.Threading.Tasks.Task<DFARMR_IVR1.GetQueryViewData.RRW3_GET_QUERY_VIEW_DATAResponse> RRW3_GET_QUERY_VIEW_DATAAsync(DFARMR_IVR1.GetQueryViewData.RRW3_GET_QUERY_VIEW_DATARequest request) {
            return base.Channel.RRW3_GET_QUERY_VIEW_DATAAsync(request);
        }
    }
}
