//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Configuration;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
using Microsoft.Web.Services3.Security.Tokens;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="ProducerValidationSoapBinding", Namespace="http://service.validation.milk.ats.com")]
public partial class ProducerValidationService : Microsoft.Web.Services3.WebServicesClientProtocol {
    
    private System.Threading.SendOrPostCallback doesProducerExistOperationCompleted;
    
    /// <remarks/>
    public ProducerValidationService() {
        string strWebserviceUrl = ConfigurationManager.AppSettings["WebServiceURL"].ToString();
        this.Url = strWebserviceUrl + "ProducerValidation";
#pragma warning disable CS0618 // 'SoapContext.Security' is obsolete: 'SoapContext.Security is obsolete. Consider deriving from SendSecurityFilter or ReceiveSecurityFilter and creating a custom policy assertion that generates these filters.'
        RequestSoapContext.Security.Tokens.Add(new UsernameToken("ivrwebsvc", "V&XT4X@L", PasswordOption.SendPlainText));
#pragma warning restore CS0618 // 'SoapContext.Security' is obsolete: 'SoapContext.Security is obsolete. Consider deriving from SendSecurityFilter or ReceiveSecurityFilter and creating a custom policy assertion that generates these filters.'
    }
    
    /// <remarks/>
    public event doesProducerExistCompletedEventHandler doesProducerExistCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.validation.milk.ats.com", ResponseNamespace="http://service.validation.milk.ats.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("doesProducerExistReturn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string doesProducerExist([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string divisionNumber, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string producerNumber) {
        object[] results = this.Invoke("doesProducerExist", new object[] {
                    divisionNumber,
                    producerNumber});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegindoesProducerExist(string divisionNumber, string producerNumber, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("doesProducerExist", new object[] {
                    divisionNumber,
                    producerNumber}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EnddoesProducerExist(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void doesProducerExistAsync(string divisionNumber, string producerNumber) {
        this.doesProducerExistAsync(divisionNumber, producerNumber, null);
    }
    
    /// <remarks/>
    public void doesProducerExistAsync(string divisionNumber, string producerNumber, object userState) {
        if ((this.doesProducerExistOperationCompleted == null)) {
            this.doesProducerExistOperationCompleted = new System.Threading.SendOrPostCallback(this.OndoesProducerExistOperationCompleted);
        }
        this.InvokeAsync("doesProducerExist", new object[] {
                    divisionNumber,
                    producerNumber}, this.doesProducerExistOperationCompleted, userState);
    }
    
    private void OndoesProducerExistOperationCompleted(object arg) {
        if ((this.doesProducerExistCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.doesProducerExistCompleted(this, new doesProducerExistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void doesProducerExistCompletedEventHandler(object sender, doesProducerExistCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class doesProducerExistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal doesProducerExistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
