//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Configuration;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
using Microsoft.Web.Services3.Security.Tokens;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="ProducerPasswordValidationSoapBinding", Namespace="http://service.validation.milk.ats.com")]
public partial class ProducerPasswordValidationService : Microsoft.Web.Services3.WebServicesClientProtocol {
    
    private System.Threading.SendOrPostCallback doesProducerPasswordExistOperationCompleted;
    
    /// <remarks/>
    public ProducerPasswordValidationService() {
        string strWebserviceUrl = ConfigurationManager.AppSettings["WebServiceURL"].ToString();
        this.Url = strWebserviceUrl + "ProducerPasswordValidation";
#pragma warning disable CS0618 // 'SoapContext.Security' is obsolete: 'SoapContext.Security is obsolete. Consider deriving from SendSecurityFilter or ReceiveSecurityFilter and creating a custom policy assertion that generates these filters.'
        RequestSoapContext.Security.Tokens.Add(new UsernameToken("ivrwebsvc", "V&XT4X@L", PasswordOption.SendPlainText));
#pragma warning restore CS0618 // 'SoapContext.Security' is obsolete: 'SoapContext.Security is obsolete. Consider deriving from SendSecurityFilter or ReceiveSecurityFilter and creating a custom policy assertion that generates these filters.'
    }
    
    /// <remarks/>
    public event doesProducerPasswordExistCompletedEventHandler doesProducerPasswordExistCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.validation.milk.ats.com", ResponseNamespace="http://service.validation.milk.ats.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("doesProducerPasswordExistReturn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string doesProducerPasswordExist([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string divisionNumber, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string producerNumber, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string producerPassword) {
        object[] results = this.Invoke("doesProducerPasswordExist", new object[] {
                    divisionNumber,
                    producerNumber,
                    producerPassword});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegindoesProducerPasswordExist(string divisionNumber, string producerNumber, string producerPassword, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("doesProducerPasswordExist", new object[] {
                    divisionNumber,
                    producerNumber,
                    producerPassword}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EnddoesProducerPasswordExist(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void doesProducerPasswordExistAsync(string divisionNumber, string producerNumber, string producerPassword) {
        this.doesProducerPasswordExistAsync(divisionNumber, producerNumber, producerPassword, null);
    }
    
    /// <remarks/>
    public void doesProducerPasswordExistAsync(string divisionNumber, string producerNumber, string producerPassword, object userState) {
        if ((this.doesProducerPasswordExistOperationCompleted == null)) {
            this.doesProducerPasswordExistOperationCompleted = new System.Threading.SendOrPostCallback(this.OndoesProducerPasswordExistOperationCompleted);
        }
        this.InvokeAsync("doesProducerPasswordExist", new object[] {
                    divisionNumber,
                    producerNumber,
                    producerPassword}, this.doesProducerPasswordExistOperationCompleted, userState);
    }
    
    private void OndoesProducerPasswordExistOperationCompleted(object arg) {
        if ((this.doesProducerPasswordExistCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.doesProducerPasswordExistCompleted(this, new doesProducerPasswordExistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void doesProducerPasswordExistCompletedEventHandler(object sender, doesProducerPasswordExistCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class doesProducerPasswordExistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal doesProducerPasswordExistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
